version: '3.7'

services:  
  mysql-server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "apiescoladb"
    ports:
      - "3306:3306"
    volumes:
      - ./.adocker/mysql/volume:/var/lib/mysql
    networks:
      - env-network

  adminer:
    image: adminer
    ports:
      - 7272:8080
    depends_on:
      - mysql-server
    networks:
      - env-network

networks: 
  env-network:
    driver: bridge
